#installation d'Apache sur le serveur de développement
- name: Installation d'Apache
  hosts: all
  tasks:
  - name: Inscrire le nouveau dépôt
    apt_repository:
      repo: deb http://ftp.fr.debian.org/debian stretch main
      state: present
      update_cache: yes
  - name: Installation d'Apache2
    apt:
      name: apache2,ca-certificates,apt-transport-https
      state: present
  - name: Démarrer le service Apache
    service:
      name: apache2
      state: started
      enabled: yes
  - name: Enregistrer une clé
    apt_key:
      url: https://packages.sury.org/php/apt.gpg
      state: present
  - name: Inscrire le dépôt pour php
    apt_repository:
      repo: deb https://packages.sury.org/php/ stretch main
      state: present
      update_cache: yes
  - name: Installation de php 7.2
    apt:
      name: php7.2
      state: present
  - name: Installation de php 7.2-mbstring
    apt:
      name: php7.2-mbstring
      state: present
  - name: Installation de php 7.2-mysqli
    apt:
      name: php7.2-mysqli
      state: present
- name: Installation de MySQL
  hosts: all
  tasks:
  - name: Installation de python-pip
    apt:
      name: python-pip
      state: present
  - name: Installation de pymssql
    pip:
      name: pymssql
  - name: Installation de python-mysqldb
    apt:
      name: python-mysqldb
      state: present
  - name: Installation de mysql-server
    apt:
      name: mysql-server
      state: present
  - name: Gestion de my.cnf
    copy:
      src: /var/www/autres/my.cnf.j2
      dest: /root/.my.cnf
      owner: root
      group: root
      mode: 0600
  - name: Gestion du mot de passe du root
    mysql_user:
      name: root
      password: btsinfo
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Création d'une base de données
    mysql_db:
      name: "{{mysql_db}}"
      state: present
      login_unix_socket: /var/run/mysqld/mysqld.sock
  - name: Création de l'utilisateur eleve et affectation des privilèges sur une base de données
    mysql_user:
      name: "{{mysql_user}}"
      password: "{{mysql_password}}"
      host: localhost
      priv: "{{mysql_db}}.*:ALL,GRANT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
- name: Installation de PhpMyAdmin
  hosts: all
  tasks:
  - name: Installation du module debconf-utils
    apt:
      name: debconf-utils
      state: present
  - name: Installation de dbconfig
    debconf:
      name: phpmyadmin
      question: phpmyadmin/dbconfig-install
      value: true
      vtype: boolean
  - name: confirmation du mot de passe
    debconf:
      name: phpmyadmin
      question: phpmyadmin/app-password-confirm
      value: btsinfo
      vtype: password
  - name: configuration du mot de passe admin
    debconf:
      name: phpmyadmin
      question: phpmyadmin/mysql/admin-pass
      value: btsinfo
      vtype: password
  - name: configuration du mot de passe utilisateur
    debconf:
      name: phpmyadmin
      question: phpmyadmin/mysql/app-pass
      value: btsinfo
      vtype: password
  - name: web server configuration
    debconf:
      name: phpmyadmin
      question: phpmyadmin/reconfigure-webserver
      value: apache2
      vtype: multiselect
  - name: Installation de PhpMyAdmin
    apt:
      name: phpmyadmin
      state: present
- name: Gestion des erreurs
  hosts: all
  tasks:
  - name: Suppression index.html
    file: 
      path: /var/www/html/index.html
      state: absent
  - name: Copie du fichier index.php
    copy:
      src: /var/www/index.php
      dest: /var/www/html/
      owner: www-data
      group: www-data
      mode: 0755
  - name: Activation de l'affichage des erreurs display_error
    lineinfile:
      dest: /etc/php/7.2/apache2/php.ini
      regexp: '^display_errors=Off'
      line: 'display_errors=On'
  - name: Activation de l'affichage des erreurs display_startup_error
    lineinfile:
      dest: /etc/php/7.2/apache2/php.ini
      regexp: '^display_startup_errors=Off'
      line: 'display_startup_errors=On'
  - name: Redémarrer le service Apache
    service:
      name: apache2
      state: restarted
      enabled: yes